{
    "cells": [
        {
            "cell_type": "markdown",
            "id": "1b87ba52",
            "metadata": {},
            "source": [
                "# AWS Neuron Benchmark on Yolov8\n",
                "\n",
                "This notebook shows how to compile Yolov8/Pytorch to AWS Inferentia (inf1 instances) using NeuronSDK.\n",
                "\n",
                "Reference: \n",
                "- Model NeuronPerf (Beta)\n",
                "    - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuronperf/index.html\n",
                "- [NeuronPerf Examples](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuronperf/neuronperf_examples.html#neuronperf-examples)    "
            ]
        },
        {
            "cell_type": "markdown",
            "id": "49acc5c3",
            "metadata": {},
            "source": [
                "## 1. Neuron Compilation using  Native Neuron SDK"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "45fd47d8",
            "metadata": {},
            "source": [
                "### Load yolo8 model using ultralytics Lib"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 1,
            "id": "ad6f3253",
            "metadata": {},
            "outputs": [
                {
                    "name": "stderr",
                    "output_type": "stream",
                    "text": [
                        "/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
                        "  from .autonotebook import tqdm as notebook_tqdm\n"
                    ]
                }
            ],
            "source": [
                "from ultralytics import YOLO\n",
                "\n",
                "model = YOLO(\"model/yolov8n.pt\", task=\"detect\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "f1a67d4a",
            "metadata": {},
            "source": [
                "### Benchmark a Compiled Model\n",
                "- [NeuronPerf Examples](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuronperf/neuronperf_examples.html#neuronperf-examples)"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "0d770ac9",
            "metadata": {},
            "source": []
        },
        {
            "cell_type": "code",
            "execution_count": 2,
            "id": "0c2e1e30",
            "metadata": {},
            "outputs": [
                {
                    "name": "stderr",
                    "output_type": "stream",
                    "text": [
                        "WARNING:neuronperf.compiling - Unable to determine a model name, using 'Model'.\n",
                        "INFO:neuronperf.compiling - Compiling batch size 1 for 1 NeuronCore(s) with performance level -1/-1. [1/1]\n"
                    ]
                },
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "New https://pypi.org/project/ultralytics/8.3.13 available üòÉ Update with 'pip install -U ultralytics'\n",
                        "Ultralytics YOLOv8.2.0 üöÄ Python-3.10.15 torch-1.13.1+cu117 CPU (Intel Xeon Platinum 8275CL 3.00GHz)\n",
                        "WARNING ‚ö†Ô∏è Upgrade to torch>=2.0.0 for deterministic training.\n",
                        "\u001b[34m\u001b[1mengine/trainer: \u001b[0mtask=detect, mode=train, model=model/yolov8n.pt, data=coco.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, fp8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, ccargs=None, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train3\n"
                    ]
                },
                {
                    "name": "stderr",
                    "output_type": "stream",
                    "text": [
                        "ERROR:neuronperf.compiling - Failed to compile input=0, batch_size=1, pipeline_size=1, perf_level=-1.\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/engine/trainer.py\", line 514, in get_dataset\n",
                        "    data = check_det_dataset(self.args.data)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/data/utils.py\", line 269, in check_det_dataset\n",
                        "    file = check_file(dataset)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/utils/checks.py\", line 499, in check_file\n",
                        "    raise FileNotFoundError(f\"'{file}' does not exist\")\n",
                        "FileNotFoundError: 'coco.yaml' does not exist\n",
                        "\n",
                        "The above exception was the direct cause of the following exception:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/compiling.py\", line 256, in compile\n",
                        "    model_filename = compile_fn(\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 35, in _compile_fn\n",
                        "    model.eval()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1930, in eval\n",
                        "    return self.train(False)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/engine/model.py\", line 654, in train\n",
                        "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/engine/trainer.py\", line 129, in __init__\n",
                        "    self.trainset, self.testset = self.get_dataset()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/ultralytics/engine/trainer.py\", line 518, in get_dataset\n",
                        "    raise RuntimeError(emojis(f\"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}\")) from e\n",
                        "RuntimeError: Dataset 'coco.yaml' error ‚ùå 'coco.yaml' does not exist\n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "'model/benchmark_yolo8_model_neuron.pt.json'"
                        ]
                    },
                    "execution_count": 2,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "import torch  # or tensorflow, mxnet\n",
                "\n",
                "import neuronperf as npf\n",
                "import neuronperf.torch  # or tensorflow, mxnet\n",
                "\n",
                "\n",
                "neuron_model_path = \"model/benchmark_yolo8_model_neuron.pt\"\n",
                "\n",
                "# Construct dummy inputs\n",
                "batch_sizes = 1\n",
                "input_shape = (batch_sizes, 3, 640, 640)\n",
                "inputs = torch.ones(input_shape)  # or numpy array for TF, MX\n",
                "\n",
                "# Benchmark and save results\n",
                "# Compile\n",
                "npf.torch.compile(\n",
                "\tmodel, \n",
                "\tinputs, \n",
                "\tbatch_sizes=batch_sizes, \n",
                "\tfilename=neuron_model_path,\n",
                ")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 4,
            "id": "1bfa6d27",
            "metadata": {},
            "outputs": [
                {
                    "name": "stderr",
                    "output_type": "stream",
                    "text": [
                        "INFO:neuronperf.benchmarking - Benchmarking 'model/traced_yolo8_model_neuron.pt', ~8.0 minutes remaining.\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 6 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 8 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 9 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 10 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 7 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 14 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 11 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 13 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 12 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 15 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "2024-Oct-15 01:18:17.0366 260688:260689 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc6-nc6 Available:0\n",
                        "2024-Oct-15 01:18:17.0378 260692:260693 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc8-nc8 Available:0\n",
                        "2024-Oct-15 01:18:17.0382 260694:260695 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc9-nc9 Available:0\n",
                        "2024-Oct-15 01:18:17.0394 260696:260697 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc10-nc10 Available:0\n",
                        "2024-Oct-15 01:18:17.0409 260690:260691 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc7-nc7 Available:0\n",
                        "2024-Oct-15 01:18:17.0417 260704:260705 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc14-nc14 Available:0\n",
                        "2024-Oct-15 01:18:17.0440 260698:260699 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc11-nc11 Available:0\n",
                        "2024-Oct-15 01:18:17.0446 260700:260701 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc12-nc12 Available:0\n",
                        "2024-Oct-15 01:18:17.0447 260702:260703 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc13-nc13 Available:0\n",
                        "2024-Oct-15 01:18:17.0473 260706:260707 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc15-nc15 Available:0\n",
                        "ERROR:neuronperf.benchmarking - Child process encountered an error:\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Failure benchmarking config: {'model_filename': 'model/traced_yolo8_model_neuron.pt', 'model_name': 'model/traced_yolo8_model_neuron.pt', 'device_type': 'neuron', 'instance_type': 'inf1.6xlarge', 'batch_size': 1, 'n_models': 16, 'workers_per_model': 1, 'pipeline_size': 1, 'n_devices': 16, 'perf_level': -1, 'multiprocess': True, 'multiinterpreter': False, 'stats_interval': '1', 'start_dts': '20241015-011817', 'max_duration': '120.0', 'max_infers': 0, 'tags': ['id_49nijlzy']}\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 1153, in benchmark\n",
                        "    results = run_benchmarkers(\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 669, in run_benchmarkers\n",
                        "    results = _run_benchmarkers_multiprocess(benchmarkers)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 609, in _run_benchmarkers_multiprocess\n",
                        "    raise ChildProcessError()\n",
                        "ChildProcessError\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 6 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 10 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 11 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 7 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 8 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 9 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 14 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 12 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 13 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Benchmarker 15 encountered an error during prep: \n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "2024-Oct-15 01:22:35.0143 261901:261902 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc6-nc6 Available:0\n",
                        "2024-Oct-15 01:22:35.0169 261909:261910 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc10-nc10 Available:0\n",
                        "2024-Oct-15 01:22:35.0183 261911:261912 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc11-nc11 Available:0\n",
                        "2024-Oct-15 01:22:35.0191 261903:261904 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc7-nc7 Available:0\n",
                        "2024-Oct-15 01:22:35.0200 261905:261906 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc8-nc8 Available:0\n",
                        "2024-Oct-15 01:22:35.0204 261907:261908 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc9-nc9 Available:0\n",
                        "2024-Oct-15 01:22:35.0239 261917:261918 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc14-nc14 Available:0\n",
                        "2024-Oct-15 01:22:35.0241 261913:261914 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc12-nc12 Available:0\n",
                        "2024-Oct-15 01:22:35.0250 261915:261916 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc13-nc13 Available:0\n",
                        "2024-Oct-15 01:22:35.0267 261919:261920 ERROR   NRT:nrt_allocate_neuron_cores               NeuronCore(s) not available - Requested:nc15-nc15 Available:0\n",
                        "ERROR:neuronperf.benchmarking - Child process encountered an error:\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 345, in run\n",
                        "    self.setup()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 244, in setup\n",
                        "    self.load()\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 181, in load\n",
                        "    self.model = self.load_fn(self.model_filename, device_id=self.device_id)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/torch/torch.py\", line 61, in _neuron_load_fn\n",
                        "    model = torch.jit.load(model_filename)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch_neuron/jit_load_wrapper.py\", line 13, in wrapper\n",
                        "    script_module = jit_load(*args, **kwargs)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/torch/jit/_serialization.py\", line 162, in load\n",
                        "    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n",
                        "RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged\n",
                        "to your system logs. See the Neuron Runtime's troubleshooting guide for help on this\n",
                        "topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/\n",
                        "\n",
                        "ERROR:neuronperf.benchmarking - Failure benchmarking config: {'model_filename': 'model/traced_yolo8_model_neuron.pt', 'model_name': 'model/traced_yolo8_model_neuron.pt', 'device_type': 'neuron', 'instance_type': 'inf1.6xlarge', 'batch_size': 1, 'n_models': 16, 'workers_per_model': 2, 'pipeline_size': 1, 'n_devices': 16, 'perf_level': -1, 'multiprocess': True, 'multiinterpreter': False, 'stats_interval': '1', 'start_dts': '20241015-012234', 'max_duration': '120.0', 'max_infers': 0, 'tags': ['id_gmucbt0i']}\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 1153, in benchmark\n",
                        "    results = run_benchmarkers(\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 669, in run_benchmarkers\n",
                        "    results = _run_benchmarkers_multiprocess(benchmarkers)\n",
                        "  File \"/home/ubuntu/miniconda3/envs/yolo8-conda-py310/lib/python3.10/site-packages/neuronperf/benchmarking.py\", line 609, in _run_benchmarkers_multiprocess\n",
                        "    raise ChildProcessError()\n",
                        "ChildProcessError\n"
                    ]
                },
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "config_tag         cost_per_1m_inf    throughput_avg     latency_ms_p50     latency_ms_p99     n_models           workers_per_model  batch_size         \n",
                        "id_nlqv2b3a        3.266              44.647             44.76              44.907             1                  2                  1                  \n",
                        "id_hgk03wvj        4.041              36.092             27.665             27.96              1                  1                  1                  \n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "'model/traced_yolo8_model_neuron.pt.results-20241015-012448.json'"
                        ]
                    },
                    "execution_count": 4,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "\n",
                "\n",
                "reports = npf.torch.benchmark(neuron_model_path, inputs, batch_sizes, \n",
                "                              duration=10, # 10 seconds\n",
                "                              )\n",
                "\n",
                "npf.print_reports(reports)\n",
                "npf.write_json(reports)"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "c0082e3a",
            "metadata": {},
            "source": [
                "## 2. Compile and inference using ultralytics lib"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "060f5dc9",
            "metadata": {},
            "source": [
                "### Load pytorch model, yolo8, and compile it to neuron model"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 6,
            "id": "793ab87d",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "Loaded existing model from model/yolov8n.neuron\n"
                    ]
                }
            ],
            "source": [
                "from ultralytics import YOLO\n",
                "\n",
                "import os\n",
                "\n",
                "pt_model_path = 'model/yolov8n.pt'\n",
                "neuron_model_path = 'model/yolov8n.neuron'\n",
                "\n",
                "if os.path.exists(neuron_model_path):\n",
                "    # Load the existing model\n",
                "    m_inf= YOLO(\"model/yolov8n.neuron\", task=\"detect\")\n",
                "    print(f\"Loaded existing model from {neuron_model_path}\")\n",
                "else:\n",
                "    mx=YOLO(pt_model_path)\n",
                "    mx.export(format=\"neuron\")\n",
                "    m_inf= YOLO(\"model/yolov8n.neuron\", task=\"detect\")\n",
                "    print(f\"Compile and Load model from pytorch model, {pt_model_path}, and neuron model, {neuron_model_path}\")\n",
                "\n"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "7b1ca898",
            "metadata": {},
            "source": [
                "### inference on neuron model"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 9,
            "id": "74a76353",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "\n",
                        "image 1/1 /home/ubuntu/lab/03-yolo8-inf1/test_image/bus.jpg: 640x640 4 persons, 1 bus, 30.4ms\n",
                        "Speed: 2.1ms preprocess, 30.4ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)\n",
                        "Results saved to \u001b[1mresult_image/predict10\u001b[0m\n",
                        "1 label saved to result_image/predict10/labels\n"
                    ]
                }
            ],
            "source": [
                "results = m_inf.predict(\"test_image/bus.jpg\", \n",
                "                            # show=True,\n",
                "                            save=True, \n",
                "                            save_txt=True, \n",
                "                            save_crop=True, \n",
                "                            save_conf=True,\n",
                "                            project='result_image')\n",
                "\n"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "f68ba52b",
            "metadata": {},
            "source": [
                "### Bounding Box information\n",
                "Refer to the link \n",
                "- [Model Prediction with Ultralytics YOLO](https://docs.ultralytics.com/modes/predict/#working-with-results)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 10,
            "id": "181884e5",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "ultralytics.engine.results.Boxes object with attributes:\n",
                        "\n",
                        "cls: tensor([0., 0., 0., 5., 0.])\n",
                        "conf: tensor([0.8909, 0.8833, 0.8779, 0.8442, 0.4408])\n",
                        "data: tensor([[6.7083e+02, 3.8008e+02, 8.0986e+02, 8.7969e+02, 8.9086e-01, 0.0000e+00],\n",
                        "        [2.2162e+02, 4.0706e+02, 3.4353e+02, 8.5626e+02, 8.8332e-01, 0.0000e+00],\n",
                        "        [5.0671e+01, 3.9760e+02, 2.4420e+02, 9.0507e+02, 8.7790e-01, 0.0000e+00],\n",
                        "        [3.1541e+01, 2.3063e+02, 8.0153e+02, 7.7584e+02, 8.4424e-01, 5.0000e+00],\n",
                        "        [4.2298e-01, 5.4981e+02, 5.7900e+01, 8.6834e+02, 4.4076e-01, 0.0000e+00]])\n",
                        "id: None\n",
                        "is_track: False\n",
                        "orig_shape: (1080, 810)\n",
                        "shape: torch.Size([5, 6])\n",
                        "xywh: tensor([[740.3431, 629.8870, 139.0354, 499.6159],\n",
                        "        [282.5750, 631.6615, 121.9024, 449.1991],\n",
                        "        [147.4372, 651.3355, 193.5327, 507.4696],\n",
                        "        [416.5346, 503.2327, 769.9878, 545.2150],\n",
                        "        [ 29.1616, 709.0754,  57.4772, 318.5244]])\n",
                        "xywhn: tensor([[0.9140, 0.5832, 0.1716, 0.4626],\n",
                        "        [0.3489, 0.5849, 0.1505, 0.4159],\n",
                        "        [0.1820, 0.6031, 0.2389, 0.4699],\n",
                        "        [0.5142, 0.4660, 0.9506, 0.5048],\n",
                        "        [0.0360, 0.6566, 0.0710, 0.2949]])\n",
                        "xyxy: tensor([[6.7083e+02, 3.8008e+02, 8.0986e+02, 8.7969e+02],\n",
                        "        [2.2162e+02, 4.0706e+02, 3.4353e+02, 8.5626e+02],\n",
                        "        [5.0671e+01, 3.9760e+02, 2.4420e+02, 9.0507e+02],\n",
                        "        [3.1541e+01, 2.3063e+02, 8.0153e+02, 7.7584e+02],\n",
                        "        [4.2298e-01, 5.4981e+02, 5.7900e+01, 8.6834e+02]])\n",
                        "xyxyn: tensor([[8.2818e-01, 3.5193e-01, 9.9983e-01, 8.1453e-01],\n",
                        "        [2.7361e-01, 3.7691e-01, 4.2411e-01, 7.9283e-01],\n",
                        "        [6.2557e-02, 3.6815e-01, 3.0149e-01, 8.3803e-01],\n",
                        "        [3.8939e-02, 2.1354e-01, 9.8954e-01, 7.1837e-01],\n",
                        "        [5.2220e-04, 5.0909e-01, 7.1482e-02, 8.0402e-01]])\n"
                    ]
                }
            ],
            "source": [
                "# View results\n",
                "for r in results:\n",
                "    print(r.boxes)  # print the Boxes object containing the detection bounding boxes"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 4,
            "id": "00fbbc97",
            "metadata": {},
            "outputs": [],
            "source": [
                "# print(\"result_inf2): \\n\", result)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "id": "d824a28c",
            "metadata": {},
            "outputs": [],
            "source": []
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "yolo8-conda-py310",
            "language": "python",
            "name": "yolo8-conda-py310"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.15"
        },
        "vscode": {
            "interpreter": {
                "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
            }
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}
